Update Test-SSH-Connection.yml

diff --git a/.github/workflows/Test-SSH-Connection.yml b/.github/workflows/Test-SSH-Connection.yml
--- a/.github/workflows/Test-SSH-Connection.yml
+++ b/.github/workflows/Test-SSH-Connection.yml
@@ -19,16 +19,22 @@ jobs:
       - name: Set up SSH key
         env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          SSH_HOST: ${{ secrets.SSH_HOST }}
         run: |
+          set -e  # Завершить выполнение скрипта при ошибке
+          echo "Setting up SSH key"
           mkdir -p ~/.ssh
           echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
-          # Добавляем хост в known_hosts, чтобы избежать предупреждения
-          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+          # Добавляем хост в known_hosts
+          echo "Adding host to known_hosts"
+          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts || { echo "Failed to add host to known_hosts"; exit 1; }
+          echo "SSH key setup complete"
 
       - name: Test SSH Connection
         env:
           SSH_USER: ${{ secrets.SSH_USER }}
           SSH_HOST: ${{ secrets.SSH_HOST }}
         run: |
+          echo "Testing SSH connection"
           ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" 'echo "SSH connection successful"'
